// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: demo.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocInfoServiceClient is the client API for DocInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocInfoServiceClient interface {
	GetDocDataInfo(ctx context.Context, in *GetDocDataInfoReq, opts ...grpc.CallOption) (*GetDocDataInfoResp, error)
}

type docInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocInfoServiceClient(cc grpc.ClientConnInterface) DocInfoServiceClient {
	return &docInfoServiceClient{cc}
}

func (c *docInfoServiceClient) GetDocDataInfo(ctx context.Context, in *GetDocDataInfoReq, opts ...grpc.CallOption) (*GetDocDataInfoResp, error) {
	out := new(GetDocDataInfoResp)
	err := c.cc.Invoke(ctx, "/demo.DocInfoService/GetDocDataInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocInfoServiceServer is the server API for DocInfoService service.
// All implementations must embed UnimplementedDocInfoServiceServer
// for forward compatibility
type DocInfoServiceServer interface {
	GetDocDataInfo(context.Context, *GetDocDataInfoReq) (*GetDocDataInfoResp, error)
	mustEmbedUnimplementedDocInfoServiceServer()
}

// UnimplementedDocInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocInfoServiceServer struct {
}

func (UnimplementedDocInfoServiceServer) GetDocDataInfo(context.Context, *GetDocDataInfoReq) (*GetDocDataInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocDataInfo not implemented")
}
func (UnimplementedDocInfoServiceServer) mustEmbedUnimplementedDocInfoServiceServer() {}

// UnsafeDocInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocInfoServiceServer will
// result in compilation errors.
type UnsafeDocInfoServiceServer interface {
	mustEmbedUnimplementedDocInfoServiceServer()
}

func RegisterDocInfoServiceServer(s grpc.ServiceRegistrar, srv DocInfoServiceServer) {
	s.RegisterService(&DocInfoService_ServiceDesc, srv)
}

func _DocInfoService_GetDocDataInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocDataInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocInfoServiceServer).GetDocDataInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.DocInfoService/GetDocDataInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocInfoServiceServer).GetDocDataInfo(ctx, req.(*GetDocDataInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DocInfoService_ServiceDesc is the grpc.ServiceDesc for DocInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.DocInfoService",
	HandlerType: (*DocInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocDataInfo",
			Handler:    _DocInfoService_GetDocDataInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
